export type CardSeed = {
  id: string;
  name: string;
  short: string;
  kind: string;
  cost: number;
  element: string;
  power?: number;
  life?: number;
  stealth?: boolean;
  unique?: boolean;
  assassinPowerBonus?: number;
  assassinStealth?: boolean;
  automaton?: boolean;
  fast?: boolean;
  floatingMemory?: boolean;
  kindle?: number;
  prepare?: number;
  aliases: string[];
};

/** Initial FiZa catalog. The engine keeps its own copy and matches these ids. */
export const CARD_SEED: CardSeed[] = [
  {
    id: "brick",
    name: "Fire Brick",
    short: "Brick",
    kind: "brick",
    cost: 9,
    element: "fire",
    aliases: ["fire_brick"],
  },
  {
    id: "arthur",
    name: "Arthur, Young Heir",
    short: "Arthu",
    kind: "ally",
    cost: 4,
    element: "fire",
    power: 2,
    life: 3,
    unique: true,
    aliases: ["arthur_young_heir"],
  },
  {
    id: "kingdom_informant",
    name: "Kingdom Informant",
    short: "Kingd",
    kind: "ally",
    cost: 2,
    element: "norm",
    power: 1,
    life: 2,
    stealth: true,
    floatingMemory: true,
    aliases: [],
  },
  {
    id: "clumsy_apprentice",
    name: "Clumsy Apprentice",
    short: "Clums",
    kind: "ally",
    cost: 2,
    element: "fire",
    power: 1,
    life: 1,
    aliases: [],
  },
  {
    id: "sable_remnant",
    name: "Sable Remnant",
    short: "Sable",
    kind: "ally",
    cost: 2,
    element: "norm",
    power: 1,
    life: 1,
    floatingMemory: true,
    assassinPowerBonus: 1,
    aliases: [],
  },
  {
    id: "hasty_messenger",
    name: "Hasty Messenger",
    short: "Hasty",
    kind: "ally",
    cost: 2,
    element: "fire",
    power: 1,
    life: 2,
    aliases: [],
  },
  {
    id: "red_hare",
    name: "Red Hare, Unrivaled Stallion",
    short: "Red H",
    kind: "ally",
    cost: 2,
    element: "fire",
    power: 3,
    life: 3,
    unique: true,
    aliases: ["red_hare_unrivaled_stallion"],
  },
  {
    id: "ignited_stab",
    name: "Ignited Stab",
    short: "Ignit",
    kind: "attack",
    cost: 1,
    element: "fire",
    power: 2,
    aliases: [],
  },
  {
    id: "rending_flames",
    name: "Rending Flames",
    short: "Rendi",
    kind: "attack",
    cost: 3,
    element: "fire",
    power: 3,
    aliases: [],
  },
  {
    id: "blazing_throw",
    name: "Blazing Throw",
    short: "Blazi",
    kind: "action",
    cost: 1,
    element: "fire",
    aliases: [],
  },
  {
    id: "corhazi_courier",
    name: "Corhazi Courier",
    short: "Corha",
    kind: "ally",
    cost: 3,
    element: "fire",
    power: 1,
    life: 2,
    stealth: true,
    aliases: ["kurhazi_courier"],
  },
  {
    id: "veteran_blazebearer",
    name: "Veteran Blazebearer",
    short: "VBlaz",
    kind: "ally",
    cost: 3,
    element: "fire",
    power: 2,
    life: 3,
    aliases: [],
  },
  {
    id: "sadi",
    name: "Sadi, Blood Harvester",
    short: "Sadi",
    kind: "ally",
    cost: 3,
    element: "norm",
    power: 2,
    life: 2,
    unique: true,
    aliases: ["sadi_blood_harvester"],
  },
  {
    id: "captivating_cutthroat",
    name: "Captivating Cutthroat",
    short: "CaptC",
    kind: "ally",
    cost: 2,
    element: "fire",
    power: 2,
    life: 1,
    assassinPowerBonus: 1,
    aliases: [],
  },
  {
    id: "dazzling_courtesan",
    name: "Dazzling Courtesan",
    short: "Dazzl",
    kind: "ally",
    cost: 3,
    element: "fire",
    power: 2,
    life: 2,
    kindle: 3,
    aliases: [],
  },
  {
    id: "fiery_interference",
    name: "Fiery Interference",
    short: "FInt",
    kind: "action",
    cost: 2,
    element: "fire",
    aliases: [],
  },
  {
    id: "heated_vengeance",
    name: "Heated Vengeance",
    short: "HeatV",
    kind: "attack",
    cost: 3,
    element: "fire",
    power: 2,
    aliases: [],
  },
  {
    id: "intensified_pyre",
    name: "Intensified Pyre",
    short: "IPyre",
    kind: "action",
    cost: 3,
    element: "fire",
    kindle: 3,
    aliases: [],
  },
  {
    id: "march_hare",
    name: "March Hare, Mottled Host",
    short: "March",
    kind: "ally",
    cost: 1,
    element: "fire",
    power: 1,
    life: 1,
    unique: true,
    aliases: ["march_hare_mottled_host"],
  },
  {
    id: "mark_the_target",
    name: "Mark the Target",
    short: "MarkT",
    kind: "action",
    cost: 1,
    element: "fire",
    aliases: [],
  },
  {
    id: "peppered_chef",
    name: "Peppered Chef",
    short: "PChef",
    kind: "ally",
    cost: 2,
    element: "fire",
    power: 2,
    life: 1,
    aliases: [],
  },
  {
    id: "planted_explosive",
    name: "Planted Explosive",
    short: "PExpl",
    kind: "action",
    cost: 2,
    element: "fire",
    prepare: 1,
    aliases: [],
  },
  {
    id: "rococo",
    name: "Rococo, Explosive Maven",
    short: "Rococ",
    kind: "ally",
    cost: 1,
    element: "fire",
    power: 1,
    life: 1,
    unique: true,
    automaton: true,
    aliases: ["rococo_explosive_maven"],
  },
  {
    id: "tweedledum",
    name: "Tweedledum, Rattled Dancer",
    short: "Tweed",
    kind: "ally",
    cost: 3,
    element: "fire",
    power: 3,
    life: 2,
    unique: true,
    assassinStealth: true,
    aliases: ["tweedledum_rattled_dancer"],
  },
  {
    id: "vermilion_decree",
    name: "Vermilion Decree",
    short: "VermD",
    kind: "action",
    cost: 3,
    element: "fire",
    aliases: [],
  },
  {
    id: "xiao_qiao",
    name: "Xiao Qiao, Cinderkeeper",
    short: "XiaoQ",
    kind: "ally",
    cost: 2,
    element: "fire",
    power: 1,
    life: 2,
    unique: true,
    stealth: true,
    aliases: ["xiao_qiao_cinderkeeper"],
  },
  {
    id: "hot_cake",
    name: "Hot Cake",
    short: "HCake",
    kind: "item",
    cost: 3,
    element: "fire",
    floatingMemory: true,
    aliases: [],
  },
  {
    id: "uncanny_realization",
    name: "Uncanny Realization",
    short: "UReal",
    kind: "attack",
    cost: 1,
    element: "norm",
    power: 3,
    aliases: [],
  },
  {
    id: "virgil",
    name: "Virgil, Altered Future",
    short: "Virgi",
    kind: "ally",
    cost: 3,
    element: "norm",
    power: 2,
    life: 2,
    unique: true,
    automaton: true,
    fast: true,
    aliases: ["virgil_altered_future"],
  },
  {
    id: "vicious_slice",
    name: "Vicious Slice",
    short: "VSlic",
    kind: "attack",
    cost: 1,
    element: "norm",
    power: 2,
    aliases: [],
  },
  {
    id: "manic_zealot",
    name: "Manic Zealot",
    short: "Manic",
    kind: "ally",
    cost: 2,
    element: "fire",
    power: 1,
    life: 1,
    automaton: true,
    aliases: [],
  },
  {
    id: "demolition",
    name: "Demolition",
    short: "Demol",
    kind: "action",
    cost: 3,
    element: "fire",
    fast: true,
    aliases: [],
  },
  {
    id: "surging_bolt",
    name: "Surging Bolt",
    short: "SBolt",
    kind: "action",
    cost: 3,
    element: "fire",
    aliases: [],
  },
  {
    id: "woodland_squirrels",
    name: "Woodland Squirrels",
    short: "Sqrls",
    kind: "ally",
    cost: 0,
    element: "norm",
    power: 1,
    life: 1,
    aliases: [],
  },
  {
    id: "duchess_six_of_hearts",
    name: "Duchess, Six of Hearts",
    short: "Duc6H",
    kind: "ally",
    cost: 6,
    element: "fire",
    power: 4,
    life: 2,
    unique: true,
    kindle: 6,
    aliases: [],
  },
  {
    id: "wandering_glaivier",
    name: "Wandering Glaivier",
    short: "WGlaiv",
    kind: "ally",
    cost: 3,
    element: "fire",
    power: 2,
    life: 1,
    aliases: [],
  },
  {
    id: "flagrant_guide",
    name: "Flagrant Guide",
    short: "FGuid",
    kind: "ally",
    cost: 3,
    element: "fire",
    power: 1,
    life: 3,
    aliases: [],
  },
];

/** Material-deck cards. Not in the engine Card enum; persist under these ids. */
export const MATERIAL_SEED: CardSeed[] = [
  {
    id: "impact_hammer",
    name: "Impact Hammer",
    short: "IHamm",
    kind: "material",
    cost: 0,
    element: "fire",
    aliases: [],
  },
  {
    id: "mercenary_blade",
    name: "Mercenary's Blade",
    short: "MBlad",
    kind: "material",
    cost: 0,
    element: "norm",
    aliases: [],
  },
  {
    id: "poisoned_dagger",
    name: "Poisoned Dagger",
    short: "PDagg",
    kind: "material",
    cost: 0,
    element: "fire",
    aliases: [],
  },
  {
    id: "zander_1",
    name: "Zander, Prepared Scout",
    short: "Zande",
    kind: "material",
    cost: 0,
    element: "fire",
    unique: true,
    aliases: ["zander"],
  },
  {
    id: "zander_2",
    name: "Zander, Deft Executor",
    short: "ZDeft",
    kind: "material",
    cost: 0,
    element: "norm",
    unique: true,
    aliases: ["zander_deft_executor"],
  },
  {
    id: "varuckan_soulknife",
    name: "Varuckan Soulknife",
    short: "VSoul",
    kind: "material",
    cost: 0,
    element: "fire",
    aliases: [],
  },
  {
    id: "tristan_1",
    name: "Tristan, Underhanded",
    short: "Trist",
    kind: "material",
    cost: 0,
    element: "fire",
    unique: true,
    aliases: ["tristan"],
  },
];

export const MATERIAL_CARD_IDS = MATERIAL_SEED.map((card) => card.id);

export function isMaterialCardId(id: string): boolean {
  return MATERIAL_CARD_IDS.includes(id);
}
