import { GENERATED_CARD_SEED } from "./generated/card-seed-data";

export type CardSeed = {
  id: string;
  name: string;
  short: string;
  kind: string;
  cost: number;
  element: string;
  power?: number;
  life?: number;
  stealth?: boolean;
  unique?: boolean;
  assassinPowerBonus?: number;
  assassinStealth?: boolean;
  automaton?: boolean;
  fast?: boolean;
  floatingMemory?: boolean;
  kindle?: number;
  prepare?: number;
  aliases: string[];
};

/** Maindeck catalog — synced from the Rust engine via `pnpm sync:cards`. */
export const CARD_SEED: CardSeed[] = GENERATED_CARD_SEED.map((card) => ({
  ...card,
  aliases: [...card.aliases],
}));

export const MATERIAL_SEED: CardSeed[] = [
  {
    id: "impact_hammer",
    name: "Impact Hammer",
    short: "IHamm",
    kind: "material",
    cost: 0,
    element: "fire",
    aliases: [],
  },
  {
    id: "mercenary_blade",
    name: "Mercenary's Blade",
    short: "MBlad",
    kind: "material",
    cost: 0,
    element: "norm",
    aliases: [],
  },
  {
    id: "poisoned_dagger",
    name: "Poisoned Dagger",
    short: "PDagg",
    kind: "material",
    cost: 0,
    element: "fire",
    aliases: [],
  },
  {
    id: "zander_1",
    name: "Zander, Prepared Scout",
    short: "Zande",
    kind: "material",
    cost: 0,
    element: "fire",
    unique: true,
    aliases: ["zander"],
  },
  {
    id: "zander_2",
    name: "Zander, Deft Executor",
    short: "ZDeft",
    kind: "material",
    cost: 0,
    element: "norm",
    unique: true,
    aliases: ["zander_deft_executor"],
  },
  {
    id: "varuckan_soulknife",
    name: "Varuckan Soulknife",
    short: "VSoul",
    kind: "material",
    cost: 0,
    element: "fire",
    aliases: [],
  },
  {
    id: "tristan_1",
    name: "Tristan, Underhanded",
    short: "Trist",
    kind: "material",
    cost: 0,
    element: "fire",
    unique: true,
    aliases: ["tristan"],
  },
  {
    id: "assassins_ripper",
    name: "Assassin's Ripper",
    short: "ARipp",
    kind: "material",
    cost: 0,
    element: "norm",
    aliases: ["assassins_ripper", "ripper"],
  },
  {
    id: "grand_crusaders_ring",
    name: "Grand Crusader's Ring",
    short: "GCRin",
    kind: "material",
    cost: 0,
    element: "norm",
    unique: true,
    aliases: ["grand_crusaders_ring", "crusaders_ring"],
  },
  {
    id: "spirit_of_fire",
    name: "Spirit of Fire",
    short: "SoFir",
    kind: "material",
    cost: 0,
    element: "fire",
    unique: true,
    aliases: ["spirit_fire"],
  },
  {
    id: "aithne_spirit_of_fire",    name: "Aithne, Spirit of Fire",
    short: "Aithn",
    kind: "material",
    cost: 0,
    element: "fire",
    unique: true,
    aliases: ["aithne"],
  },
  {
    id: "hanabi_spirit_of_fire",
    name: "Hanabi, Spirit of Fire",
    short: "Hanab",
    kind: "material",
    cost: 0,
    element: "fire",
    unique: true,
    aliases: ["hanabi"],
  },
  {
    id: "vyra_spirit_of_fire",
    name: "Vyra, Spirit of Fire",
    short: "Vyra",
    kind: "material",
    cost: 0,
    element: "fire",
    unique: true,
    aliases: ["vyra"],
  },
  {
    id: "rai_spellcrafter",
    name: "Rai, Spellcrafter",
    short: "Rai1",
    kind: "material",
    cost: 0,
    element: "norm",
    unique: true,
    aliases: ["rai"],
  },
  {
    id: "rai_archmage",
    name: "Rai, Archmage",
    short: "Rai2",
    kind: "material",
    cost: 0,
    element: "norm",
    unique: true,
    aliases: ["rai_archmage"],
  },
  {
    id: "rai_mana_weaver",
    name: "Rai, Mana Weaver",
    short: "Rai3",
    kind: "material",
    cost: 0,
    element: "arcane",
    unique: true,
    aliases: ["rai_mana_weaver"],
  },
  {
    id: "rai_storm_seer",
    name: "Rai, Storm Seer",
    short: "RaiS",
    kind: "material",
    cost: 0,
    element: "arcane",
    unique: true,
    aliases: ["rai_storm_seer"],
  },
  {
    id: "kongming_wayward_maven",
    name: "Kongming, Wayward Maven",
    short: "Kong1",
    kind: "material",
    cost: 0,
    element: "norm",
    unique: true,
    aliases: ["kongming"],
  },
  {
    id: "kongming_erudite_strategist",
    name: "Kongming, Erudite Strategist",
    short: "Kong2",
    kind: "material",
    cost: 0,
    element: "norm",
    unique: true,
    aliases: ["kongming_erudite"],
  },
  {
    id: "kongming_ascetic_vice",
    name: "Kongming, Ascetic Vice",
    short: "Kong3",
    kind: "material",
    cost: 0,
    element: "norm",
    unique: true,
    aliases: ["kongming_ascetic"],
  },
  {
    id: "dante_prodigal_swain",
    name: "Dante, Prodigal Swain",
    short: "Dant1",
    kind: "material",
    cost: 0,
    element: "norm",
    unique: true,
    aliases: ["dante"],
  },
  {
    id: "dante_aenean_initiate",
    name: "Dante, Aenean Initiate",
    short: "Dant2",
    kind: "material",
    cost: 0,
    element: "norm",
    unique: true,
    aliases: ["dante_aenean"],
  },
  {
    id: "dante_hemomancer",
    name: "Dante, Hemomancer",
    short: "Dant3",
    kind: "material",
    cost: 0,
    element: "exia",
    unique: true,
    aliases: ["dante_hemomancer"],
  },
  {
    id: "dante_hematic_overdrive",
    name: "Dante, Hematic Overdrive",
    short: "Dant4",
    kind: "material",
    cost: 0,
    element: "exia",
    unique: true,
    aliases: ["dante_hematic"],
  },
  {
    id: "tonoris_lone_mercenary",
    name: "Tonoris, Lone Mercenary",
    short: "Tono1",
    kind: "material",
    cost: 0,
    element: "norm",
    unique: true,
    aliases: ["tonoris"],
  },
  {
    id: "tonoris_might_of_humanity",
    name: "Tonoris, Might of Humanity",
    short: "Tono2",
    kind: "material",
    cost: 0,
    element: "norm",
    unique: true,
    aliases: ["tonoris_might"],
  },
  {
    id: "tonoris_genesis_aegis",
    name: "Tonoris, Genesis Aegis",
    short: "Tono3",
    kind: "material",
    cost: 0,
    element: "neos",
    unique: true,
    aliases: ["tonoris_genesis"],
  },
  {
    id: "tonoris_creations_will",
    name: "Tonoris, Creation's Will",
    short: "Tono4",
    kind: "material",
    cost: 0,
    element: "neos",
    unique: true,
    aliases: ["tonoris_creation"],
  },
  {
    id: "backup_charger",
    name: "Backup Charger",
    short: "BChar",
    kind: "material",
    cost: 0,
    element: "norm",
    aliases: [],
  },
  {
    id: "cell_reactor",
    name: "Cell Reactor",
    short: "CReac",
    kind: "material",
    cost: 0,
    element: "norm",
    aliases: [],
  },
  {
    id: "mercurial_heart",
    name: "Mercurial Heart",
    short: "MHear",
    kind: "material",
    cost: 0,
    element: "norm",
    unique: true,
    aliases: [],
  },
  {
    id: "synthetic_core",
    name: "Synthetic Core",
    short: "SCore",
    kind: "material",
    cost: 0,
    element: "norm",
    aliases: [],
  },
  {
    id: "deployment_beacon",
    name: "Deployment Beacon",
    short: "DBeac",
    kind: "material",
    cost: 0,
    element: "wind",
    aliases: [],
  },
  {
    id: "sentinel_fabricator",
    name: "Sentinel Fabricator",
    short: "SFabr",
    kind: "material",
    cost: 0,
    element: "neos",
    aliases: [],
  },
  {
    id: "worn_gearblade",
    name: "Worn Gearblade",
    short: "WGear",
    kind: "material",
    cost: 0,
    element: "norm",
    aliases: [],
  },
  {
    id: "reciprocity_dorumegias_call",
    name: "Reciprocity, Dorumegia's Call",
    short: "Recip",
    kind: "material",
    cost: 0,
    element: "norm",
    aliases: ["reciprocity"],
  },
  {
    id: "synth_disrupter",
    name: "Synth Disrupter",
    short: "SDisp",
    kind: "material",
    cost: 0,
    element: "norm",
    aliases: [],
  },
  {
    id: "aegis_of_dawn",
    name: "Aegis of Dawn",
    short: "ADawn",
    kind: "material",
    cost: 0,
    element: "neos",
    aliases: [],
  },
];

export const MATERIAL_CARD_IDS = MATERIAL_SEED.map((card) => card.id);

export function isMaterialCardId(id: string): boolean {
  return MATERIAL_CARD_IDS.includes(id);
}
