//! Static card registry — one entry per card.

use super::def::CatalogEntry;
use super::effects::{Cond, Effect};
use super::keywords::Keyword;
use super::kind::CardKind;
use super::Card;

/// Canonical catalog ordered by [`Card`] discriminant.
pub static CATALOG: [CatalogEntry; super::CARD_COUNT] = [
    CatalogEntry {
        card: Card::Brick,
        id: "brick",
        name: "Fire Brick",
        short: "Brick",
        kind: CardKind::Brick,
        cost: 9,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &["fire_brick"],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::Arthur,
        id: "arthur",
        name: "Arthur, Young Heir",
        short: "Arthu",
        kind: CardKind::Ally,
        cost: 4,
        fire: true,
        power: 2,
        life: Some(3),
        keywords: &[Keyword::Unique],
        aliases: &["arthur_young_heir"],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::KingdomInformant,
        id: "kingdom_informant",
        name: "Kingdom Informant",
        short: "Kingd",
        kind: CardKind::Ally,
        cost: 2,
        fire: false,
        power: 1,
        life: Some(2),
        keywords: &[Keyword::Stealth, Keyword::FloatingMemory],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::ClumsyApprentice,
        id: "clumsy_apprentice",
        name: "Clumsy Apprentice",
        short: "Clums",
        kind: CardKind::Ally,
        cost: 2,
        fire: true,
        power: 1,
        life: Some(1),
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[
            Effect::Draw,
        ],
    },
    CatalogEntry {
        card: Card::SableRemnant,
        id: "sable_remnant",
        name: "Sable Remnant",
        short: "Sable",
        kind: CardKind::Ally,
        cost: 2,
        fire: false,
        power: 1,
        life: Some(1),
        keywords: &[Keyword::FloatingMemory, Keyword::AssassinPowerBonus(1)],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::HastyMessenger,
        id: "hasty_messenger",
        name: "Hasty Messenger",
        short: "Hasty",
        kind: CardKind::Ally,
        cost: 2,
        fire: true,
        power: 1,
        life: Some(2),
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::RedHare,
        id: "red_hare",
        name: "Red Hare, Unrivaled Stallion",
        short: "Red H",
        kind: CardKind::Ally,
        cost: 2,
        fire: true,
        power: 3,
        life: Some(3),
        keywords: &[Keyword::Unique],
        aliases: &["red_hare_unrivaled_stallion"],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::IgnitedStab,
        id: "ignited_stab",
        name: "Ignited Stab",
        short: "Ignit",
        kind: CardKind::Attack,
        cost: 1,
        fire: true,
        power: 2,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::RendingFlames,
        id: "rending_flames",
        name: "Rending Flames",
        short: "Rendi",
        kind: CardKind::Attack,
        cost: 3,
        fire: true,
        power: 3,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::BlazingThrow,
        id: "blazing_throw",
        name: "Blazing Throw",
        short: "Blazi",
        kind: CardKind::Action,
        cost: 1,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::CorhaziCourier,
        id: "corhazi_courier",
        name: "Corhazi Courier",
        short: "Corha",
        kind: CardKind::Ally,
        cost: 3,
        fire: true,
        power: 1,
        life: Some(2),
        keywords: &[Keyword::Stealth],
        aliases: &["kurhazi_courier"],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::VeteranBlazebearer,
        id: "veteran_blazebearer",
        name: "Veteran Blazebearer",
        short: "VBlaz",
        kind: CardKind::Ally,
        cost: 3,
        fire: true,
        power: 2,
        life: Some(3),
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::Sadi,
        id: "sadi",
        name: "Sadi, Blood Harvester",
        short: "Sadi",
        kind: CardKind::Ally,
        cost: 3,
        fire: false,
        power: 2,
        life: Some(2),
        keywords: &[Keyword::Unique],
        aliases: &["sadi_blood_harvester"],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::CaptivatingCutthroat,
        id: "captivating_cutthroat",
        name: "Captivating Cutthroat",
        short: "CaptC",
        kind: CardKind::Ally,
        cost: 2,
        fire: true,
        power: 2,
        life: Some(1),
        keywords: &[Keyword::AssassinPowerBonus(1)],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::DazzlingCourtesan,
        id: "dazzling_courtesan",
        name: "Dazzling Courtesan",
        short: "Dazzl",
        kind: CardKind::Ally,
        cost: 3,
        fire: true,
        power: 2,
        life: Some(2),
        keywords: &[Keyword::Kindle(3)],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::FieryInterference,
        id: "fiery_interference",
        name: "Fiery Interference",
        short: "FInt",
        kind: CardKind::Action,
        cost: 2,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[
            Effect::Damage(2),
        ],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::HeatedVengeance,
        id: "heated_vengeance",
        name: "Heated Vengeance",
        short: "HeatV",
        kind: CardKind::Attack,
        cost: 3,
        fire: true,
        power: 2,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::IntensifiedPyre,
        id: "intensified_pyre",
        name: "Intensified Pyre",
        short: "IPyre",
        kind: CardKind::Action,
        cost: 3,
        fire: true,
        power: 0,
        life: None,
        keywords: &[Keyword::Fast, Keyword::Kindle(3)],
        aliases: &[],
        on_play: &[
            Effect::DamageIf { cond: Cond::GyAtLeast(8), then_n: 6, else_n: 2 },
        ],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::MarchHare,
        id: "march_hare",
        name: "March Hare, Mottled Host",
        short: "March",
        kind: CardKind::Ally,
        cost: 1,
        fire: true,
        power: 1,
        life: Some(1),
        keywords: &[Keyword::Unique],
        aliases: &["march_hare_mottled_host"],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::MarkTheTarget,
        id: "mark_the_target",
        name: "Mark the Target",
        short: "MarkT",
        kind: CardKind::Action,
        cost: 1,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[
            Effect::Damage(1),
            Effect::AddPrepIf { cond: Cond::IsAssassin, n: 1 },
        ],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::PepperedChef,
        id: "peppered_chef",
        name: "Peppered Chef",
        short: "PChef",
        kind: CardKind::Ally,
        cost: 2,
        fire: true,
        power: 2,
        life: Some(1),
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::PlantedExplosive,
        id: "planted_explosive",
        name: "Planted Explosive",
        short: "PExpl",
        kind: CardKind::Action,
        cost: 2,
        fire: true,
        power: 0,
        life: None,
        keywords: &[Keyword::Prepare(1)],
        aliases: &[],
        on_play: &[
            Effect::DamageIf { cond: Cond::Prepared, then_n: 4, else_n: 2 },
        ],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::Rococo,
        id: "rococo",
        name: "Rococo, Explosive Maven",
        short: "Rococ",
        kind: CardKind::Ally,
        cost: 1,
        fire: true,
        power: 1,
        life: Some(1),
        keywords: &[Keyword::Unique, Keyword::Automaton],
        aliases: &["rococo_explosive_maven"],
        on_play: &[],
        on_enter: &[
            Effect::DamageIf { cond: Cond::InfluenceAtMost(4), then_n: 2, else_n: 0 },
        ],
    },
    CatalogEntry {
        card: Card::Tweedledum,
        id: "tweedledum",
        name: "Tweedledum, Rattled Dancer",
        short: "Tweed",
        kind: CardKind::Ally,
        cost: 3,
        fire: true,
        power: 3,
        life: Some(2),
        keywords: &[Keyword::Unique, Keyword::AssassinStealth],
        aliases: &["tweedledum_rattled_dancer"],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::VermilionDecree,
        id: "vermilion_decree",
        name: "Vermilion Decree",
        short: "VermD",
        kind: CardKind::Action,
        cost: 3,
        fire: true,
        power: 0,
        life: None,
        keywords: &[Keyword::Fast, Keyword::Imbue(3)],
        aliases: &[],
        on_play: &[
            Effect::Damage(3),
            Effect::DrawIf { cond: Cond::Imbued },
        ],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::XiaoQiao,
        id: "xiao_qiao",
        name: "Xiao Qiao, Cinderkeeper",
        short: "XiaoQ",
        kind: CardKind::Ally,
        cost: 2,
        fire: true,
        power: 1,
        life: Some(2),
        keywords: &[Keyword::Unique, Keyword::Stealth],
        aliases: &["xiao_qiao_cinderkeeper"],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::HotCake,
        id: "hot_cake",
        name: "Hot Cake",
        short: "HCake",
        kind: CardKind::Item,
        cost: 3,
        fire: true,
        power: 0,
        life: None,
        keywords: &[Keyword::FloatingMemory],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::UncannyRealization,
        id: "uncanny_realization",
        name: "Uncanny Realization",
        short: "UReal",
        kind: CardKind::Attack,
        cost: 1,
        fire: false,
        power: 3,
        life: None,
        keywords: &[Keyword::CommandAutomaton],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::Virgil,
        id: "virgil",
        name: "Virgil, Altered Future",
        short: "Virgi",
        kind: CardKind::Ally,
        cost: 3,
        fire: false,
        power: 2,
        life: Some(2),
        keywords: &[Keyword::Unique, Keyword::Fast, Keyword::Automaton],
        aliases: &["virgil_altered_future"],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::ViciousSlice,
        id: "vicious_slice",
        name: "Vicious Slice",
        short: "VSlic",
        kind: CardKind::Attack,
        cost: 1,
        fire: false,
        power: 2,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::ManicZealot,
        id: "manic_zealot",
        name: "Manic Zealot",
        short: "Manic",
        kind: CardKind::Ally,
        cost: 2,
        fire: true,
        power: 1,
        life: Some(1),
        keywords: &[Keyword::Automaton, Keyword::OnDeathDamage(2)],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::Demolition,
        id: "demolition",
        name: "Demolition",
        short: "Demol",
        kind: CardKind::Action,
        cost: 3,
        fire: true,
        power: 0,
        life: None,
        keywords: &[Keyword::Fast],
        aliases: &[],
        on_play: &[
            Effect::Damage(3),
        ],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::SurgingBolt,
        id: "surging_bolt",
        name: "Surging Bolt",
        short: "SBolt",
        kind: CardKind::Action,
        cost: 3,
        fire: true,
        power: 0,
        life: None,
        keywords: &[Keyword::Imbue(3)],
        aliases: &[],
        on_play: &[
            Effect::DamageIf { cond: Cond::Imbued, then_n: 4, else_n: 3 },
        ],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::WoodlandSquirrels,
        id: "woodland_squirrels",
        name: "Woodland Squirrels",
        short: "Sqrls",
        kind: CardKind::Ally,
        cost: 0,
        fire: false,
        power: 1,
        life: Some(1),
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::DuchessSixOfHearts,
        id: "duchess_six_of_hearts",
        name: "Duchess, Six of Hearts",
        short: "Duc6H",
        kind: CardKind::Ally,
        cost: 6,
        fire: true,
        power: 4,
        life: Some(2),
        keywords: &[Keyword::Unique, Keyword::Kindle(6)],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::WanderingGlaivier,
        id: "wandering_glaivier",
        name: "Wandering Glaivier",
        short: "WGlaiv",
        kind: CardKind::Ally,
        cost: 3,
        fire: true,
        power: 2,
        life: Some(1),
        keywords: &[Keyword::OnDeathDraw],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::FlagrantGuide,
        id: "flagrant_guide",
        name: "Flagrant Guide",
        short: "FGuid",
        kind: CardKind::Ally,
        cost: 3,
        fire: true,
        power: 1,
        life: Some(3),
        keywords: &[Keyword::OnEnterLevel],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::Gildas,
        id: "gildas",
        name: "Gildas, Chronicler of Aesa",
        short: "Gilda",
        kind: CardKind::Ally,
        cost: 3,
        fire: false,
        power: 1,
        life: Some(3),
        keywords: &[Keyword::Unique],
        aliases: &["gildas_chronicler_of_aesa"],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::Incapacitate,
        id: "incapacitate",
        name: "Incapacitate",
        short: "Incap",
        kind: CardKind::Action,
        cost: 4,
        fire: false,
        power: 0,
        life: None,
        keywords: &[Keyword::Fast],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::LurkingAssailant,
        id: "lurking_assailant",
        name: "Lurking Assailant",
        short: "Lurki",
        kind: CardKind::Ally,
        cost: 3,
        fire: false,
        power: 2,
        life: Some(3),
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::UndeniableTruth,
        id: "undeniable_truth",
        name: "Undeniable Truth",
        short: "Unden",
        kind: CardKind::Action,
        cost: 1,
        fire: false,
        power: 0,
        life: None,
        keywords: &[Keyword::Fast],
        aliases: &[],
        on_play: &[
            Effect::Draw,
            Effect::AddPrep(1),
        ],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::CorhaziArsonist,
        id: "corhazi_arsonist",
        name: "Corhazi Arsonist",
        short: "Arson",
        kind: CardKind::Ally,
        cost: 3,
        fire: true,
        power: 2,
        life: Some(2),
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::IgniteFate,
        id: "ignite_fate",
        name: "Ignite Fate",
        short: "IFate",
        kind: CardKind::Action,
        cost: 3,
        fire: true,
        power: 0,
        life: None,
        keywords: &[Keyword::FloatingMemory],
        aliases: &[],
        on_play: &[
            Effect::SetChampionDamaged,
            Effect::Damage(2),
        ],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::IncreasingDanger,
        id: "increasing_danger",
        name: "Increasing Danger",
        short: "IDang",
        kind: CardKind::Action,
        cost: 2,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[
            Effect::Draw,
            Effect::DrawToMemory,
        ],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::ReduceToAsh,
        id: "reduce_to_ash",
        name: "Reduce to Ash",
        short: "RtAsh",
        kind: CardKind::Action,
        cost: 3,
        fire: true,
        power: 0,
        life: None,
        keywords: &[Keyword::Fast],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::SmokeOut,
        id: "smoke_out",
        name: "Smoke Out",
        short: "Smoke",
        kind: CardKind::Action,
        cost: 1,
        fire: true,
        power: 0,
        life: None,
        keywords: &[Keyword::Fast],
        aliases: &[],
        on_play: &[
            Effect::Damage(1),
        ],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::SparkAlight,
        id: "spark_alight",
        name: "Spark Alight",
        short: "Spark",
        kind: CardKind::Action,
        cost: 2,
        fire: true,
        power: 0,
        life: None,
        keywords: &[Keyword::Fast],
        aliases: &["aenean_spark_alight"],
        on_play: &[
            Effect::Damage(2),
        ],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::PackageCourier,
        id: "package_courier",
        name: "Package Courier",
        short: "PCour",
        kind: CardKind::Ally,
        cost: 2,
        fire: true,
        power: 1,
        life: Some(3),
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::FlurryOfFire,
        id: "flurry_of_fire",
        name: "Aenean Flurry of Fire",
        short: "Flurr",
        kind: CardKind::Action,
        cost: 2,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &["aenean_flurry_of_fire"],
        on_play: &[
            Effect::DamageRepeated { amount: 1, times: 2 },
        ],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::CreativeShock,
        id: "creative_shock",
        name: "Creative Shock",
        short: "Shock",
        kind: CardKind::Action,
        cost: 3,
        fire: true,
        power: 0,
        life: None,
        keywords: &[Keyword::Fast],
        aliases: &[],
        on_play: &[
            Effect::Draw,
            Effect::Draw,
            Effect::DiscardForEffect,
        ],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::Fireball,
        id: "fireball",
        name: "Fireball",
        short: "Fireb",
        kind: CardKind::Action,
        cost: 4,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::SpontaneousCombustion,
        id: "spontaneous_combustion",
        name: "Spontaneous Combustion",
        short: "SC",
        kind: CardKind::Action,
        cost: 3,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[Effect::Damage(4)],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::FocusedFlames,
        id: "focused_flames",
        name: "Focused Flames",
        short: "FF",
        kind: CardKind::Action,
        cost: 2,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[Effect::Damage(4)],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::StraightFlare,
        id: "straight_flare",
        name: "Straight Flare",
        short: "SF",
        kind: CardKind::Action,
        cost: 2,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::ScorchingKnowledge,
        id: "scorching_knowledge",
        name: "Scorching Knowledge",
        short: "SK",
        kind: CardKind::Action,
        cost: 1,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::SetAblaze,
        id: "set_ablaze",
        name: "Set Ablaze",
        short: "SA",
        kind: CardKind::Action,
        cost: 2,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[Effect::Damage(4)],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::ThermalBreak,
        id: "thermal_break",
        name: "Thermal Break",
        short: "TB",
        kind: CardKind::Action,
        cost: 3,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::BlazeAlight,
        id: "blaze_alight",
        name: "Blaze Alight",
        short: "BA",
        kind: CardKind::Action,
        cost: 2,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[Effect::Damage(3)],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::PurgeInFlames,
        id: "purge_in_flames",
        name: "Purge in Flames",
        short: "PiF",
        kind: CardKind::Action,
        cost: 8,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[Effect::Damage(2)],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::Disintegrate,
        id: "disintegrate",
        name: "Disintegrate",
        short: "Disin",
        kind: CardKind::Action,
        cost: 8,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::FoundPower,
        id: "found_power",
        name: "Found Power",
        short: "FP",
        kind: CardKind::Action,
        cost: 1,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::CremationRitual,
        id: "cremation_ritual",
        name: "Cremation Ritual",
        short: "CR",
        kind: CardKind::Action,
        cost: 3,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[Effect::Draw, Effect::Draw],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::MoltenEcho,
        id: "molten_echo",
        name: "Molten Echo",
        short: "ME",
        kind: CardKind::Action,
        cost: 2,
        fire: true,
        power: 0,
        life: None,
        keywords: &[Keyword::Kindle(2)],
        aliases: &[],
        on_play: &[Effect::Damage(1)],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::RestoringEmbers,
        id: "restoring_embers",
        name: "Restoring Embers",
        short: "RE",
        kind: CardKind::Action,
        cost: 4,
        fire: true,
        power: 0,
        life: None,
        keywords: &[Keyword::Kindle(4)],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::RapidCombustion,
        id: "rapid_combustion",
        name: "Rapid Combustion",
        short: "RC",
        kind: CardKind::Action,
        cost: 4,
        fire: true,
        power: 0,
        life: None,
        keywords: &[Keyword::Kindle(4)],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::SilentFirebrand,
        id: "silent_firebrand",
        name: "Silent Firebrand",
        short: "SF",
        kind: CardKind::Ally,
        cost: 4,
        fire: true,
        power: 3,
        life: Some(1),
        keywords: &[Keyword::Kindle(2)],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::BurningAethercharge,
        id: "burning_aethercharge",
        name: "Burning Aethercharge",
        short: "BA",
        kind: CardKind::Action,
        cost: 2,
        fire: true,
        power: 1,
        life: None,
        keywords: &[Keyword::Kindle(2)],
        aliases: &[],
        on_play: &[Effect::Damage(2)],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::SpurnToAsh,
        id: "spurn_to_ash",
        name: "Spurn to Ash",
        short: "StA",
        kind: CardKind::Action,
        cost: 3,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::Excoriate,
        id: "excoriate",
        name: "Excoriate",
        short: "Excor",
        kind: CardKind::Action,
        cost: 4,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::InnervateFury,
        id: "innervate_fury",
        name: "Innervate Fury",
        short: "IF",
        kind: CardKind::Action,
        cost: 3,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[Effect::Damage(7)],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::AshenRiffle,
        id: "ashen_riffle",
        name: "Ashen Riffle",
        short: "AR",
        kind: CardKind::Action,
        cost: 2,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::CreativeTinder,
        id: "creative_tinder",
        name: "Creative Tinder",
        short: "CT",
        kind: CardKind::Action,
        cost: 3,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[Effect::Draw, Effect::Draw, Effect::DiscardForEffect],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::Lavastorm,
        id: "lavastorm",
        name: "Lavastorm",
        short: "Lavas",
        kind: CardKind::Action,
        cost: 4,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::Thunderclap,
        id: "thunderclap",
        name: "Thunderclap",
        short: "Thund",
        kind: CardKind::Action,
        cost: 4,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[Effect::Damage(4)],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::GildedPyre,
        id: "gilded_pyre",
        name: "Gilded Pyre",
        short: "GP",
        kind: CardKind::Action,
        cost: 2,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[Effect::Damage(2)],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::Escharotomy,
        id: "escharotomy",
        name: "Escharotomy",
        short: "Escha",
        kind: CardKind::Action,
        cost: 1,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::PyroclasticFlow,
        id: "pyroclastic_flow",
        name: "Pyroclastic Flow",
        short: "PF",
        kind: CardKind::Action,
        cost: 4,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[Effect::Damage(2)],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::EruptingRhapsody,
        id: "erupting_rhapsody",
        name: "Erupting Rhapsody",
        short: "ER",
        kind: CardKind::Action,
        cost: 2,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::SacredEngulfment,
        id: "sacred_engulfment",
        name: "Sacred Engulfment",
        short: "SE",
        kind: CardKind::Action,
        cost: 3,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::SolarPinnacle,
        id: "solar_pinnacle",
        name: "Solar Pinnacle",
        short: "SP",
        kind: CardKind::Action,
        cost: 2,
        fire: true,
        power: 0,
        life: None,
        keywords: &[Keyword::Fast],
        aliases: &[],
        on_play: &[Effect::Damage(2)],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::IgniteSoul,
        id: "ignite_the_soul",
        name: "Ignite the Soul",
        short: "ItS",
        kind: CardKind::Action,
        cost: 1,
        fire: true,
        power: 0,
        life: None,
        keywords: &[Keyword::FloatingMemory],
        aliases: &[],
        on_play: &[Effect::Damage(1)],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::AeneanPointedFlare,
        id: "aenean_pointed_flare",
        name: "Aenean Pointed Flare",
        short: "APF",
        kind: CardKind::Action,
        cost: 4,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[Effect::Damage(4)],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::AeneanScorchingComet,
        id: "aenean_scorching_comet",
        name: "Aenean Scorching Comet",
        short: "ASC",
        kind: CardKind::Action,
        cost: 2,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[Effect::Damage(2)],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::FlaredIridescence,
        id: "flared_iridescence",
        name: "Flared Iridescence",
        short: "FI",
        kind: CardKind::Action,
        cost: 2,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[Effect::Damage(4)],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::PyreticPrognosis,
        id: "pyretic_prognosis",
        name: "Pyretic Prognosis",
        short: "PP",
        kind: CardKind::Action,
        cost: 3,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[Effect::Draw, Effect::Draw, Effect::Draw, Effect::DiscardForEffect],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::EquanimitySAshes,
        id: "equanimity_s_ashes",
        name: "Equanimity's Ashes",
        short: "EsA",
        kind: CardKind::Action,
        cost: 5,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[Effect::Damage(3)],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::ScorchedConquest,
        id: "scorched_conquest",
        name: "Scorched Conquest",
        short: "SC",
        kind: CardKind::Action,
        cost: 3,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::ClaudeFatedVisionary,
        id: "claude_fated_visionary",
        name: "Claude, Fated Visionary",
        short: "CFV",
        kind: CardKind::Ally,
        cost: 3,
        fire: false,
        power: 0,
        life: Some(2),
        keywords: &[Keyword::Unique],
        aliases: &["claude"],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::CordeliaAurousKaiser,
        id: "cordelia_aurous_kaiser",
        name: "Cordelia, Aurous Kaiser",
        short: "CAK",
        kind: CardKind::Ally,
        cost: 5,
        fire: false,
        power: 3,
        life: Some(4),
        keywords: &[Keyword::Unique],
        aliases: &["cordelia"],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::HarvesterMkII,
        id: "harvester_mk_ii",
        name: "Harvester Mk II",
        short: "HMI",
        kind: CardKind::Ally,
        cost: 3,
        fire: false,
        power: 1,
        life: Some(2),
        keywords: &[Keyword::Unique, Keyword::Automaton],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::OverlordMkIII,
        id: "overlord_mk_iii",
        name: "Overlord Mk III",
        short: "OMI",
        kind: CardKind::Ally,
        cost: 4,
        fire: false,
        power: 5,
        life: Some(5),
        keywords: &[Keyword::Unique, Keyword::Automaton],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::AcademyAttendant,
        id: "academy_attendant",
        name: "Academy Attendant",
        short: "AA",
        kind: CardKind::Ally,
        cost: 3,
        fire: false,
        power: 2,
        life: Some(2),
        keywords: &[Keyword::Automaton],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::CellProduction,
        id: "cell_production",
        name: "Cell Production",
        short: "CP",
        kind: CardKind::Action,
        cost: 3,
        fire: false,
        power: 0,
        life: None,
        keywords: &[Keyword::Automaton],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::ManufactureCell,
        id: "manufacture_cell",
        name: "Manufacture Cell",
        short: "MC",
        kind: CardKind::Action,
        cost: 2,
        fire: false,
        power: 0,
        life: None,
        keywords: &[Keyword::Automaton],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::TuneUp,
        id: "tune_up",
        name: "Tune Up",
        short: "TU",
        kind: CardKind::Action,
        cost: 2,
        fire: false,
        power: 0,
        life: None,
        keywords: &[Keyword::Automaton, Keyword::FloatingMemory],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::TurboCharge,
        id: "turbo_charge",
        name: "Turbo Charge",
        short: "TC",
        kind: CardKind::Action,
        cost: 3,
        fire: false,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[Effect::Draw, Effect::Draw],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::CounterInterference,
        id: "counter_interference",
        name: "Counter Interference",
        short: "CI",
        kind: CardKind::Action,
        cost: 2,
        fire: false,
        power: 0,
        life: None,
        keywords: &[Keyword::Automaton],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::CriticalRecovery,
        id: "critical_recovery",
        name: "Critical Recovery",
        short: "CR",
        kind: CardKind::Action,
        cost: 2,
        fire: false,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::Reprogram,
        id: "reprogram",
        name: "Reprogram",
        short: "Repro",
        kind: CardKind::Action,
        cost: 2,
        fire: false,
        power: 0,
        life: None,
        keywords: &[Keyword::FloatingMemory],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::Powercell,
        id: "powercell",
        name: "Powercell",
        short: "Power",
        kind: CardKind::Item,
        cost: 1,
        fire: false,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::AutomatonDrone,
        id: "automaton_drone",
        name: "Automaton Drone",
        short: "AD",
        kind: CardKind::Ally,
        cost: 1,
        fire: false,
        power: 1,
        life: Some(1),
        keywords: &[Keyword::Automaton],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::AutomatedGardener,
        id: "automated_gardener",
        name: "Automated Gardener",
        short: "AG",
        kind: CardKind::Ally,
        cost: 3,
        fire: false,
        power: 2,
        life: Some(3),
        keywords: &[Keyword::Automaton],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::CaretakerDrone,
        id: "caretaker_drone",
        name: "Caretaker Drone",
        short: "CD",
        kind: CardKind::Ally,
        cost: 2,
        fire: false,
        power: 0,
        life: Some(2),
        keywords: &[Keyword::Automaton],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::FurnaceDrone,
        id: "furnace_drone",
        name: "Furnace Drone",
        short: "FD",
        kind: CardKind::Ally,
        cost: 3,
        fire: true,
        power: 3,
        life: Some(4),
        keywords: &[Keyword::Automaton],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::FiretunedAutomaton,
        id: "firetuned_automaton",
        name: "Firetuned Automaton",
        short: "FA",
        kind: CardKind::Ally,
        cost: 2,
        fire: true,
        power: 3,
        life: Some(1),
        keywords: &[Keyword::Automaton, Keyword::FloatingMemory],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::PoweredSentinel,
        id: "powered_sentinel",
        name: "Powered Sentinel",
        short: "PS",
        kind: CardKind::Ally,
        cost: 3,
        fire: true,
        power: 2,
        life: Some(3),
        keywords: &[Keyword::Automaton],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::PoweredDefender,
        id: "powered_defender",
        name: "Powered Defender",
        short: "PD",
        kind: CardKind::Ally,
        cost: 3,
        fire: false,
        power: 1,
        life: Some(4),
        keywords: &[Keyword::Automaton],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::Shieldroid,
        id: "shieldroid",
        name: "Shieldroid",
        short: "Shiel",
        kind: CardKind::Ally,
        cost: 2,
        fire: false,
        power: 0,
        life: Some(2),
        keywords: &[Keyword::Automaton, Keyword::FloatingMemory],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::NoviceMechanist,
        id: "novice_mechanist",
        name: "Novice Mechanist",
        short: "NM",
        kind: CardKind::Ally,
        cost: 2,
        fire: false,
        power: 1,
        life: Some(2),
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::CellConverter,
        id: "cell_converter",
        name: "Cell Converter",
        short: "CC",
        kind: CardKind::Ally,
        cost: 3,
        fire: false,
        power: 0,
        life: Some(3),
        keywords: &[Keyword::Automaton, Keyword::FloatingMemory],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::CellAssembler,
        id: "cell_assembler",
        name: "Cell Assembler",
        short: "CA",
        kind: CardKind::Ally,
        cost: 2,
        fire: false,
        power: 2,
        life: Some(1),
        keywords: &[Keyword::Automaton],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::CellGenerator,
        id: "cell_generator",
        name: "Cell Generator",
        short: "CG",
        kind: CardKind::Ally,
        cost: 3,
        fire: false,
        power: 1,
        life: Some(3),
        keywords: &[Keyword::Automaton],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::CellForging,
        id: "cell_forging",
        name: "Cell Forging",
        short: "CF",
        kind: CardKind::Action,
        cost: 3,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::ReactivateDrone,
        id: "reactivate_drone",
        name: "Reactivate Drone",
        short: "RD",
        kind: CardKind::Action,
        cost: 2,
        fire: false,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::SummonSentinels,
        id: "summon_sentinels",
        name: "Summon Sentinels",
        short: "SS",
        kind: CardKind::Action,
        cost: 4,
        fire: false,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::BolsterRanks,
        id: "bolster_ranks",
        name: "Bolster Ranks",
        short: "BR",
        kind: CardKind::Action,
        cost: 3,
        fire: false,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::AssembleAncients,
        id: "assemble_the_ancients",
        name: "Assemble the Ancients",
        short: "AtA",
        kind: CardKind::Action,
        cost: 3,
        fire: false,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::TriumphantMechanic,
        id: "triumphant_mechanic",
        name: "Triumphant Mechanic",
        short: "TM",
        kind: CardKind::Ally,
        cost: 3,
        fire: false,
        power: 1,
        life: Some(4),
        keywords: &[Keyword::Automaton],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::SordelleUnmooredException,
        id: "sordelle_unmoored_exception",
        name: "Sordelle, Unmoored Exception",
        short: "SUE",
        kind: CardKind::Ally,
        cost: 3,
        fire: false,
        power: 1,
        life: Some(3),
        keywords: &[Keyword::Unique],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::GeniGiftedMechanist,
        id: "geni_gifted_mechanist",
        name: "Geni, Gifted Mechanist",
        short: "GGM",
        kind: CardKind::Ally,
        cost: 3,
        fire: false,
        power: 0,
        life: Some(2),
        keywords: &[Keyword::Unique],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::InzaliUnshackledBlaze,
        id: "inzali_unshackled_blaze",
        name: "Inzali, Unshackled Blaze",
        short: "IUB",
        kind: CardKind::Ally,
        cost: 3,
        fire: true,
        power: 1,
        life: Some(4),
        keywords: &[Keyword::Unique, Keyword::Automaton],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::VoldaSmolderSSpite,
        id: "volda_smolder_s_spite",
        name: "Volda, Smolder's Spite",
        short: "VSsS",
        kind: CardKind::Ally,
        cost: 2,
        fire: true,
        power: 1,
        life: Some(3),
        keywords: &[Keyword::Unique, Keyword::Automaton, Keyword::Fast],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::HectorPraetorianGuard,
        id: "hector_praetorian_guard",
        name: "Hector, Praetorian Guard",
        short: "HPG",
        kind: CardKind::Ally,
        cost: 3,
        fire: false,
        power: 3,
        life: Some(3),
        keywords: &[Keyword::Unique, Keyword::Imbue(3)],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::AtmosArmorTypeAres,
        id: "atmos_armor_type_ares",
        name: "Atmos Armor Type-Ares",
        short: "AATA",
        kind: CardKind::Ally,
        cost: 3,
        fire: false,
        power: 1,
        life: Some(5),
        keywords: &[Keyword::Unique, Keyword::Automaton],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::AtmosArmorTypeHermes,
        id: "atmos_armor_type_hermes",
        name: "Atmos Armor Type-Hermes",
        short: "AATH",
        kind: CardKind::Ally,
        cost: 3,
        fire: false,
        power: 2,
        life: Some(2),
        keywords: &[Keyword::Unique, Keyword::Automaton],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::TitanMkII,
        id: "titan_mk_ii",
        name: "Titan Mk II",
        short: "TMI",
        kind: CardKind::Ally,
        cost: 3,
        fire: false,
        power: 3,
        life: Some(3),
        keywords: &[Keyword::Automaton],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    }
];
