//! Static card registry — one entry per card.

use super::def::CatalogEntry;
use super::effects::{Cond, Effect};
use super::keywords::Keyword;
use super::kind::CardKind;
use super::Card;

/// Canonical catalog ordered by [`Card`] discriminant.
pub static CATALOG: [CatalogEntry; super::CARD_COUNT] = [
    CatalogEntry {
        card: Card::Brick,
        id: "brick",
        name: "Fire Brick",
        short: "Brick",
        kind: CardKind::Brick,
        cost: 9,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &["fire_brick"],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::Arthur,
        id: "arthur",
        name: "Arthur, Young Heir",
        short: "Arthu",
        kind: CardKind::Ally,
        cost: 4,
        fire: true,
        power: 2,
        life: Some(3),
        keywords: &[Keyword::Unique],
        aliases: &["arthur_young_heir"],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::KingdomInformant,
        id: "kingdom_informant",
        name: "Kingdom Informant",
        short: "Kingd",
        kind: CardKind::Ally,
        cost: 2,
        fire: false,
        power: 1,
        life: Some(2),
        keywords: &[Keyword::Stealth, Keyword::FloatingMemory],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::ClumsyApprentice,
        id: "clumsy_apprentice",
        name: "Clumsy Apprentice",
        short: "Clums",
        kind: CardKind::Ally,
        cost: 2,
        fire: true,
        power: 1,
        life: Some(1),
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[
            Effect::Draw,
        ],
    },
    CatalogEntry {
        card: Card::SableRemnant,
        id: "sable_remnant",
        name: "Sable Remnant",
        short: "Sable",
        kind: CardKind::Ally,
        cost: 2,
        fire: false,
        power: 1,
        life: Some(1),
        keywords: &[Keyword::FloatingMemory, Keyword::AssassinPowerBonus(1)],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::HastyMessenger,
        id: "hasty_messenger",
        name: "Hasty Messenger",
        short: "Hasty",
        kind: CardKind::Ally,
        cost: 2,
        fire: true,
        power: 1,
        life: Some(2),
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::RedHare,
        id: "red_hare",
        name: "Red Hare, Unrivaled Stallion",
        short: "Red H",
        kind: CardKind::Ally,
        cost: 2,
        fire: true,
        power: 3,
        life: Some(3),
        keywords: &[Keyword::Unique],
        aliases: &["red_hare_unrivaled_stallion"],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::IgnitedStab,
        id: "ignited_stab",
        name: "Ignited Stab",
        short: "Ignit",
        kind: CardKind::Attack,
        cost: 1,
        fire: true,
        power: 2,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::RendingFlames,
        id: "rending_flames",
        name: "Rending Flames",
        short: "Rendi",
        kind: CardKind::Attack,
        cost: 3,
        fire: true,
        power: 3,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::BlazingThrow,
        id: "blazing_throw",
        name: "Blazing Throw",
        short: "Blazi",
        kind: CardKind::Action,
        cost: 1,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::CorhaziCourier,
        id: "corhazi_courier",
        name: "Corhazi Courier",
        short: "Corha",
        kind: CardKind::Ally,
        cost: 3,
        fire: true,
        power: 1,
        life: Some(2),
        keywords: &[Keyword::Stealth],
        aliases: &["kurhazi_courier"],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::VeteranBlazebearer,
        id: "veteran_blazebearer",
        name: "Veteran Blazebearer",
        short: "VBlaz",
        kind: CardKind::Ally,
        cost: 3,
        fire: true,
        power: 2,
        life: Some(3),
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::Sadi,
        id: "sadi",
        name: "Sadi, Blood Harvester",
        short: "Sadi",
        kind: CardKind::Ally,
        cost: 3,
        fire: false,
        power: 2,
        life: Some(2),
        keywords: &[Keyword::Unique],
        aliases: &["sadi_blood_harvester"],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::CaptivatingCutthroat,
        id: "captivating_cutthroat",
        name: "Captivating Cutthroat",
        short: "CaptC",
        kind: CardKind::Ally,
        cost: 2,
        fire: true,
        power: 2,
        life: Some(1),
        keywords: &[Keyword::AssassinPowerBonus(1)],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::DazzlingCourtesan,
        id: "dazzling_courtesan",
        name: "Dazzling Courtesan",
        short: "Dazzl",
        kind: CardKind::Ally,
        cost: 3,
        fire: true,
        power: 2,
        life: Some(2),
        keywords: &[Keyword::Kindle(3)],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::FieryInterference,
        id: "fiery_interference",
        name: "Fiery Interference",
        short: "FInt",
        kind: CardKind::Action,
        cost: 2,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[
            Effect::Damage(2),
        ],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::HeatedVengeance,
        id: "heated_vengeance",
        name: "Heated Vengeance",
        short: "HeatV",
        kind: CardKind::Attack,
        cost: 3,
        fire: true,
        power: 2,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::IntensifiedPyre,
        id: "intensified_pyre",
        name: "Intensified Pyre",
        short: "IPyre",
        kind: CardKind::Action,
        cost: 3,
        fire: true,
        power: 0,
        life: None,
        keywords: &[Keyword::Fast, Keyword::Kindle(3)],
        aliases: &[],
        on_play: &[
            Effect::DamageIf { cond: Cond::GyAtLeast(8), then_n: 6, else_n: 2 },
        ],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::MarchHare,
        id: "march_hare",
        name: "March Hare, Mottled Host",
        short: "March",
        kind: CardKind::Ally,
        cost: 1,
        fire: true,
        power: 1,
        life: Some(1),
        keywords: &[Keyword::Unique],
        aliases: &["march_hare_mottled_host"],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::MarkTheTarget,
        id: "mark_the_target",
        name: "Mark the Target",
        short: "MarkT",
        kind: CardKind::Action,
        cost: 1,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[
            Effect::Damage(1),
            Effect::AddPrepIf { cond: Cond::IsAssassin, n: 1 },
        ],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::PepperedChef,
        id: "peppered_chef",
        name: "Peppered Chef",
        short: "PChef",
        kind: CardKind::Ally,
        cost: 2,
        fire: true,
        power: 2,
        life: Some(1),
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::PlantedExplosive,
        id: "planted_explosive",
        name: "Planted Explosive",
        short: "PExpl",
        kind: CardKind::Action,
        cost: 2,
        fire: true,
        power: 0,
        life: None,
        keywords: &[Keyword::Prepare(1)],
        aliases: &[],
        on_play: &[
            Effect::DamageIf { cond: Cond::Prepared, then_n: 4, else_n: 2 },
        ],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::Rococo,
        id: "rococo",
        name: "Rococo, Explosive Maven",
        short: "Rococ",
        kind: CardKind::Ally,
        cost: 1,
        fire: true,
        power: 1,
        life: Some(1),
        keywords: &[Keyword::Unique, Keyword::Automaton],
        aliases: &["rococo_explosive_maven"],
        on_play: &[],
        on_enter: &[
            Effect::DamageIf { cond: Cond::InfluenceAtMost(4), then_n: 2, else_n: 0 },
        ],
    },
    CatalogEntry {
        card: Card::Tweedledum,
        id: "tweedledum",
        name: "Tweedledum, Rattled Dancer",
        short: "Tweed",
        kind: CardKind::Ally,
        cost: 3,
        fire: true,
        power: 3,
        life: Some(2),
        keywords: &[Keyword::Unique, Keyword::AssassinStealth],
        aliases: &["tweedledum_rattled_dancer"],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::VermilionDecree,
        id: "vermilion_decree",
        name: "Vermilion Decree",
        short: "VermD",
        kind: CardKind::Action,
        cost: 3,
        fire: true,
        power: 0,
        life: None,
        keywords: &[Keyword::Fast, Keyword::Imbue(3)],
        aliases: &[],
        on_play: &[
            Effect::Damage(3),
            Effect::DrawIf { cond: Cond::Imbued },
        ],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::XiaoQiao,
        id: "xiao_qiao",
        name: "Xiao Qiao, Cinderkeeper",
        short: "XiaoQ",
        kind: CardKind::Ally,
        cost: 2,
        fire: true,
        power: 1,
        life: Some(2),
        keywords: &[Keyword::Unique, Keyword::Stealth],
        aliases: &["xiao_qiao_cinderkeeper"],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::HotCake,
        id: "hot_cake",
        name: "Hot Cake",
        short: "HCake",
        kind: CardKind::Item,
        cost: 3,
        fire: true,
        power: 0,
        life: None,
        keywords: &[Keyword::FloatingMemory],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::UncannyRealization,
        id: "uncanny_realization",
        name: "Uncanny Realization",
        short: "UReal",
        kind: CardKind::Attack,
        cost: 1,
        fire: false,
        power: 3,
        life: None,
        keywords: &[Keyword::CommandAutomaton],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::Virgil,
        id: "virgil",
        name: "Virgil, Altered Future",
        short: "Virgi",
        kind: CardKind::Ally,
        cost: 3,
        fire: false,
        power: 2,
        life: Some(2),
        keywords: &[Keyword::Unique, Keyword::Fast, Keyword::Automaton],
        aliases: &["virgil_altered_future"],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::ViciousSlice,
        id: "vicious_slice",
        name: "Vicious Slice",
        short: "VSlic",
        kind: CardKind::Attack,
        cost: 1,
        fire: false,
        power: 2,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::ManicZealot,
        id: "manic_zealot",
        name: "Manic Zealot",
        short: "Manic",
        kind: CardKind::Ally,
        cost: 2,
        fire: true,
        power: 1,
        life: Some(1),
        keywords: &[Keyword::Automaton, Keyword::OnDeathDamage(2)],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::Demolition,
        id: "demolition",
        name: "Demolition",
        short: "Demol",
        kind: CardKind::Action,
        cost: 3,
        fire: true,
        power: 0,
        life: None,
        keywords: &[Keyword::Fast],
        aliases: &[],
        on_play: &[
            Effect::Damage(3),
        ],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::SurgingBolt,
        id: "surging_bolt",
        name: "Surging Bolt",
        short: "SBolt",
        kind: CardKind::Action,
        cost: 3,
        fire: true,
        power: 0,
        life: None,
        keywords: &[Keyword::Imbue(3)],
        aliases: &[],
        on_play: &[
            Effect::DamageIf { cond: Cond::Imbued, then_n: 4, else_n: 3 },
        ],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::WoodlandSquirrels,
        id: "woodland_squirrels",
        name: "Woodland Squirrels",
        short: "Sqrls",
        kind: CardKind::Ally,
        cost: 0,
        fire: false,
        power: 1,
        life: Some(1),
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::DuchessSixOfHearts,
        id: "duchess_six_of_hearts",
        name: "Duchess, Six of Hearts",
        short: "Duc6H",
        kind: CardKind::Ally,
        cost: 6,
        fire: true,
        power: 4,
        life: Some(2),
        keywords: &[Keyword::Unique, Keyword::Kindle(6)],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::WanderingGlaivier,
        id: "wandering_glaivier",
        name: "Wandering Glaivier",
        short: "WGlaiv",
        kind: CardKind::Ally,
        cost: 3,
        fire: true,
        power: 2,
        life: Some(1),
        keywords: &[Keyword::OnDeathDraw],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::FlagrantGuide,
        id: "flagrant_guide",
        name: "Flagrant Guide",
        short: "FGuid",
        kind: CardKind::Ally,
        cost: 3,
        fire: true,
        power: 1,
        life: Some(3),
        keywords: &[Keyword::OnEnterLevel],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::Gildas,
        id: "gildas",
        name: "Gildas, Chronicler of Aesa",
        short: "Gilda",
        kind: CardKind::Ally,
        cost: 3,
        fire: false,
        power: 1,
        life: Some(3),
        keywords: &[Keyword::Unique],
        aliases: &["gildas_chronicler_of_aesa"],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::Incapacitate,
        id: "incapacitate",
        name: "Incapacitate",
        short: "Incap",
        kind: CardKind::Action,
        cost: 4,
        fire: false,
        power: 0,
        life: None,
        keywords: &[Keyword::Fast],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::LurkingAssailant,
        id: "lurking_assailant",
        name: "Lurking Assailant",
        short: "Lurki",
        kind: CardKind::Ally,
        cost: 3,
        fire: false,
        power: 2,
        life: Some(3),
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::UndeniableTruth,
        id: "undeniable_truth",
        name: "Undeniable Truth",
        short: "Unden",
        kind: CardKind::Action,
        cost: 1,
        fire: false,
        power: 0,
        life: None,
        keywords: &[Keyword::Fast],
        aliases: &[],
        on_play: &[
            Effect::Draw,
            Effect::AddPrep(1),
        ],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::CorhaziArsonist,
        id: "corhazi_arsonist",
        name: "Corhazi Arsonist",
        short: "Arson",
        kind: CardKind::Ally,
        cost: 3,
        fire: true,
        power: 2,
        life: Some(2),
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::IgniteFate,
        id: "ignite_fate",
        name: "Ignite Fate",
        short: "IFate",
        kind: CardKind::Action,
        cost: 3,
        fire: true,
        power: 0,
        life: None,
        keywords: &[Keyword::FloatingMemory],
        aliases: &[],
        on_play: &[
            Effect::SetChampionDamaged,
            Effect::Damage(2),
        ],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::IncreasingDanger,
        id: "increasing_danger",
        name: "Increasing Danger",
        short: "IDang",
        kind: CardKind::Action,
        cost: 2,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &[],
        on_play: &[
            Effect::Draw,
            Effect::DrawToMemory,
        ],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::ReduceToAsh,
        id: "reduce_to_ash",
        name: "Reduce to Ash",
        short: "RtAsh",
        kind: CardKind::Action,
        cost: 3,
        fire: true,
        power: 0,
        life: None,
        keywords: &[Keyword::Fast],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::SmokeOut,
        id: "smoke_out",
        name: "Smoke Out",
        short: "Smoke",
        kind: CardKind::Action,
        cost: 1,
        fire: true,
        power: 0,
        life: None,
        keywords: &[Keyword::Fast],
        aliases: &[],
        on_play: &[
            Effect::Damage(1),
        ],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::SparkAlight,
        id: "spark_alight",
        name: "Spark Alight",
        short: "Spark",
        kind: CardKind::Action,
        cost: 2,
        fire: true,
        power: 0,
        life: None,
        keywords: &[Keyword::Fast],
        aliases: &["aenean_spark_alight"],
        on_play: &[
            Effect::Damage(2),
        ],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::PackageCourier,
        id: "package_courier",
        name: "Package Courier",
        short: "PCour",
        kind: CardKind::Ally,
        cost: 2,
        fire: true,
        power: 1,
        life: Some(3),
        keywords: &[],
        aliases: &[],
        on_play: &[],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::FlurryOfFire,
        id: "flurry_of_fire",
        name: "Aenean Flurry of Fire",
        short: "Flurr",
        kind: CardKind::Action,
        cost: 2,
        fire: true,
        power: 0,
        life: None,
        keywords: &[],
        aliases: &["aenean_flurry_of_fire"],
        on_play: &[
            Effect::DamageRepeated { amount: 1, times: 2 },
        ],
        on_enter: &[],
    },
    CatalogEntry {
        card: Card::CreativeShock,
        id: "creative_shock",
        name: "Creative Shock",
        short: "Shock",
        kind: CardKind::Action,
        cost: 3,
        fire: true,
        power: 0,
        life: None,
        keywords: &[Keyword::Fast],
        aliases: &[],
        on_play: &[
            Effect::Draw,
            Effect::Draw,
            Effect::DiscardForEffect,
        ],
        on_enter: &[],
    },
];

