import type { CardId, MaterialId } from "@/lib/engine/types";

const GATCG_ORIGIN = "https://api.gatcg.com";

/** GATCG edition image paths for catalog cards with official art. */
const CARD_IMAGE_PATHS: Partial<Record<CardId | MaterialId, string>> = {
  arthur: "/cards/images/vn9fgfiy38.jpg",
  kingdom_informant: "/cards/images/wdxi74wb4y.jpg",
  clumsy_apprentice: "/cards/images/Gsl57juAHW.jpg",
  sable_remnant: "/cards/images/2ahEr0UKmG.jpg",
  hasty_messenger: "/cards/images/zb25m5c8lj.jpg",
  red_hare: "/cards/images/fokw35hv3j.jpg",
  ignited_stab: "/cards/images/8izzioxgug.jpg",
  rending_flames: "/cards/images/OiOzavefYK.jpg",
  blazing_throw: "/cards/images/129pcx7uyc.jpg",
  corhazi_courier: "/cards/images/s3572jtod1.jpg",
  veteran_blazebearer: "/cards/images/ijq63nobfs.jpg",
  sadi: "/cards/images/KyHItYENpc.jpg",
  captivating_cutthroat: "/cards/images/1h4pzmq492.jpg",
  dazzling_courtesan: "/cards/images/trg8idr6s7.jpg",
  fiery_interference: "/cards/images/in1rj6qet0.jpg",
  heated_vengeance: "/cards/images/1x041sk6lk.jpg",
  intensified_pyre: "/cards/images/p90l7heq7j.jpg",
  march_hare: "/cards/images/qxvut6f4ix.jpg",
  mark_the_target: "/cards/images/lztmw3rrii.jpg",
  peppered_chef: "/cards/images/giaidsyfgn.jpg",
  planted_explosive: "/cards/images/zevpnv6hwn.jpg",
  rococo: "/cards/images/p8m8o1j194.jpg",
  tweedledum: "/cards/images/ZtRu29fO87.jpg",
  vermilion_decree: "/cards/images/yrc9a8c16b.jpg",
  xiao_qiao: "/cards/images/dw4hsb2t91.jpg",
  hot_cake: "/cards/images/1W0SJDzIvQ.jpg",
  uncanny_realization: "/cards/images/zUDtPfAGKw.jpg",
  virgil: "/cards/images/yX6Ri6mnDg.jpg",
  vicious_slice: "/cards/images/5m6sqe6kd7.jpg",
  manic_zealot: "/cards/images/rcdzdhnf18.jpg",
  demolition: "/cards/images/o56arxxu83.jpg",
  surging_bolt: "/cards/images/h5lahljr2d.jpg",
  woodland_squirrels: "/cards/images/UyNpsv41nN.jpg",
  duchess_six_of_hearts: "/cards/images/gxw0q94fym.jpg",
  wandering_glaivier: "/cards/images/paqm8uowyt.jpg",
  flagrant_guide: "/cards/images/24uRBjFtiS.jpg",
  gildas: "/cards/images/IkO7g0Bazt.jpg",
  incapacitate: "/cards/images/0LdKeO0ujD.jpg",
  lurking_assailant: "/cards/images/p59ez88jmo.jpg",
  undeniable_truth: "/cards/images/MBGFdCJIcT.jpg",
  corhazi_arsonist: "/cards/images/nsdvlwz1vc.jpg",
  ignite_fate: "/cards/images/xaZiVP2rZd.jpg",
  increasing_danger: "/cards/images/uhsxfhcc8f.jpg",
  reduce_to_ash: "/cards/images/87aqv0lut4.jpg",
  smoke_out: "/cards/images/pmo37yoti9.jpg",
  spark_alight: "/cards/images/xYuivRUbwA.jpg",
  impact_hammer: "/cards/images/nkcqjdmuih.jpg",
  mercenary_blade: "/cards/images/evrbdzdhmf.jpg",
  poisoned_dagger: "/cards/images/ua6rsfsw2v.jpg",
  zander_1: "/cards/images/07vvmdvbku.jpg",
  zander_2: "/cards/images/xvzpkpasit.jpg",
  varuckan_soulknife: "/cards/images/jxhktrfo66.jpg",
  assassins_ripper: "/cards/images/isxy5li23q.jpg",
  grand_crusaders_ring: "/cards/images/ioxgugw9r9.jpg",
  tristan_1: "/cards/images/5dgq56cjg0.jpg",
};

export function cardImageUrl(id: CardId | MaterialId | string): string | null {
  const path = CARD_IMAGE_PATHS[id as CardId | MaterialId];
  return path ? `${GATCG_ORIGIN}${path}` : null;
}
